// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import BarChartOutlined from 'C:/WorkSpace/VS_WorkSpace/bi-frontend-main/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import CrownOutlined from 'C:/WorkSpace/VS_WorkSpace/bi-frontend-main/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'C:/WorkSpace/VS_WorkSpace/bi-frontend-main/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { BarChartOutlined, CrownOutlined, TableOutlined };
