// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import AreaChartOutlined from 'C:/WorkSpace/VS_WorkSpace/bi-frontend-main/node_modules/@ant-design/icons/es/icons/AreaChartOutlined';
import BarChartOutlined from 'C:/WorkSpace/VS_WorkSpace/bi-frontend-main/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import ApartmentOutlined from 'C:/WorkSpace/VS_WorkSpace/bi-frontend-main/node_modules/@ant-design/icons/es/icons/ApartmentOutlined';
import FolderOpenOutlined from 'C:/WorkSpace/VS_WorkSpace/bi-frontend-main/node_modules/@ant-design/icons/es/icons/FolderOpenOutlined';
import CrownOutlined from 'C:/WorkSpace/VS_WorkSpace/bi-frontend-main/node_modules/@ant-design/icons/es/icons/CrownOutlined';
export default { AreaChartOutlined, BarChartOutlined, ApartmentOutlined, FolderOpenOutlined, CrownOutlined };
